# Generated by Django 6.0.5 on 2026-06-07 06:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resize', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.CharField(max_length=100, verbose_name='申请人')),
                ('domain', models.CharField(max_length=255, unique=True, verbose_name='域名')),
                ('backend_ip', models.GenericIPAddressField(verbose_name='后端IP地址')),
                ('port', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)], verbose_name='后端端口')),
                ('reason', models.TextField(verbose_name='申请原因')),
                ('approval_status', models.CharField(choices=[('pending', '待审批'), ('approved', '已批准'), ('rejected', '已驳回')], default='pending', max_length=20, verbose_name='审批状态')),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='审批人')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('reject_reason', models.TextField(blank=True, null=True, verbose_name='驳回原因')),
                ('status', models.CharField(choices=[('pending_approval', '待审批'), ('approved', '已批准'), ('rejected', '已驳回'), ('pending', '待执行'), ('running', '执行中'), ('success', '成功'), ('failed', '失败')], default='pending_approval', max_length=20, verbose_name='任务状态')),
                ('result', models.TextField(blank=True, null=True, verbose_name='执行结果')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('finish_time', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
            ],
            options={
                'verbose_name': '域名配置任务',
                'verbose_name_plural': '域名配置任务',
                'ordering': ['-id'],
            },
        ),
    ]
