# Generated by Django 6.0.5 on 2026-09-10 08:58
#
# 漂移修复迁移：DiskResizeTask 的 disk_key/disk_label/drive_letter/
# approval_status/approved_by/approved_at/reject_reason 七个字段在
# 0001-0004 迁移中缺失（生产库为手工补列）。
# 部署说明：生产库因列已存在，需先执行
#   python manage.py migrate resize 0005 --fake
# 标记后，再正常 migrate；全新部署直接 migrate。

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resize', '0004_diskresizetask_datastore_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diskresizetask',
            options={'ordering': ['-id'], 'verbose_name': '磁盘扩容任务', 'verbose_name_plural': '磁盘扩容任务'},
        ),
        migrations.AddField(
            model_name='diskresizetask',
            name='approval_status',
            field=models.CharField(choices=[('pending', '待审批'), ('auto_approved', '自动批准'), ('approved', '管理员批准'), ('rejected', '已驳回')], default='pending', max_length=20, verbose_name='审批状态'),
        ),
        migrations.AddField(
            model_name='diskresizetask',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审批时间'),
        ),
        migrations.AddField(
            model_name='diskresizetask',
            name='approved_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='审批人'),
        ),
        migrations.AddField(
            model_name='diskresizetask',
            name='disk_key',
            field=models.CharField(default='', help_text='vCenter SCSI 磁盘标识', max_length=50, verbose_name='磁盘标识'),
        ),
        migrations.AddField(
            model_name='diskresizetask',
            name='disk_label',
            field=models.CharField(default='', help_text='vCenter 磁盘显示名称', max_length=100, verbose_name='磁盘标签'),
        ),
        migrations.AddField(
            model_name='diskresizetask',
            name='drive_letter',
            field=models.CharField(blank=True, default='', max_length=1, verbose_name='盘符'),
        ),
        migrations.AddField(
            model_name='diskresizetask',
            name='reject_reason',
            field=models.TextField(blank=True, null=True, verbose_name='驳回原因'),
        ),
        migrations.AlterField(
            model_name='diskresizetask',
            name='add_size',
            field=models.IntegerField(verbose_name='扩容大小(GB)'),
        ),
        migrations.AlterField(
            model_name='diskresizetask',
            name='applicant',
            field=models.CharField(max_length=100, verbose_name='申请人'),
        ),
        migrations.AlterField(
            model_name='diskresizetask',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='diskresizetask',
            name='current_size',
            field=models.IntegerField(verbose_name='当前大小(GB)'),
        ),
        migrations.AlterField(
            model_name='diskresizetask',
            name='finish_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='完成时间'),
        ),
        migrations.AlterField(
            model_name='diskresizetask',
            name='reason',
            field=models.TextField(verbose_name='申请原因'),
        ),
        migrations.AlterField(
            model_name='diskresizetask',
            name='result',
            field=models.TextField(blank=True, null=True, verbose_name='执行结果'),
        ),
        migrations.AlterField(
            model_name='diskresizetask',
            name='status',
            field=models.CharField(choices=[('pending_approval', '待审批'), ('approved', '已批准'), ('rejected', '已驳回'), ('pending', '待执行'), ('running', '执行中'), ('success', '成功'), ('failed', '失败')], default='pending_approval', max_length=20, verbose_name='任务状态'),
        ),
        migrations.AlterField(
            model_name='diskresizetask',
            name='vm_ip',
            field=models.GenericIPAddressField(verbose_name='虚拟机IP'),
        ),
    ]
