# Generated by Django 6.0.5 on 2026-09-10 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resize', '0005_diskresizetask_missing_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(max_length=50, verbose_name='序号')),
                ('change_type', models.CharField(choices=[('db_param', '数据库参数调整'), ('server_migration', '服务器迁移'), ('firewall_policy', '防火墙策略调整'), ('core_switch', '核心交换配置修改'), ('system_upgrade', '业务系统升级'), ('app_config', '应用配置修改'), ('service_param', '服务参数调整'), ('permission', '权限调整'), ('script', '脚本修改'), ('other', '其他')], max_length=20, verbose_name='变更类型')),
                ('server_ip', models.CharField(help_text='多台用英文逗号分隔', max_length=500, verbose_name='操作服务器IP')),
                ('reason', models.TextField(verbose_name='变更原因')),
                ('impact_scope', models.TextField(verbose_name='可能影响范围')),
                ('rollback_plan', models.TextField(blank=True, default='', verbose_name='回退方案')),
                ('level', models.CharField(choices=[('major', '重大变更'), ('normal', '一般变更'), ('routine', '日常操作')], default='routine', editable=False, max_length=10, verbose_name='级别')),
                ('applicant', models.CharField(max_length=100, verbose_name='操作人')),
                ('approval_status', models.CharField(choices=[('approved', '已同意')], default='approved', max_length=20, verbose_name='审批')),
                ('approved_by', models.CharField(default='system', max_length=100, verbose_name='审批人')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('implement_time', models.DateTimeField(auto_now_add=True, verbose_name='实施时间')),
            ],
            options={
                'verbose_name': '变更记录',
                'verbose_name_plural': '变更记录',
                'ordering': ['-id'],
            },
        ),
    ]
