"""
Django settings for h8667_vmplatform project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 延迟导入 hpjx_sso，避免在设置加载前访问 settings
# import hpjx.hpjx_sso

CELERY_BROKER_URL = 'redis://@x.x.20.143:6379/0'
CELERY_RESULT_BACKEND = 'redis://@x.x.20.143:6379/1'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Shanghai'
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-d=h!$@&b#*(@piwbpllo@#3xu6*^r&+s2qh$mm%a8cmmp17u4l'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# CSRF trusted origins for SSO integration
CSRF_TRUSTED_ORIGINS = [
    'https://vmplatform.XXXX.com',
    'https://sso.XXXX.com',
    'http://vmplatform.XXXX.com',
    'https://dev.sso.XXXX.com',
]

VCENTER_CONFIG = {
    'HOST': "x.x.2.40",
    'USERNAME': "administrator@vsphere.local",
    'PASSWORD': "NettrixXXXX.",
}
ANSIBLE_CONFIG = {

    'HOST': 'x.x.20.226',
    'USERNAME': 'xxxx',
    'PASSWORD': 'xxxxxxxx',
    'WORKDIR': '/etc/ansible',
    'PLAYBOOK': 'playbooks/windows_extend.yml',
    'windows_list': 'inventory.d/windows_dynamic.ini',
    'INVENTORY': 'hosts',
}

# Windows 服务器授权登录（AD 域控）配置
AD_CONFIG = {
    'DOMAIN': 'hp4307.com',
    'NETBIOS': 'hp4307',
    'USERNAME': 'hp4307\\bakadmin',
    'PASSWORD': '1qazxsw@',
    'SEARCH_BASE': 'DC=HP4307,DC=com',
    # 文件日志目录（与原运维脚本保持一致）
    'LOG_DIR': r'D:\logs\ywops\server',
}

# 设置受信任站点（WinRM + 组策略 GPO）配置
TRUST_SITE_CONFIG = {
    'HOST': '192.168.2.86',
    'NETBIOS': 'hp4307',
    'USERNAME': 'bakadmin',
    'PASSWORD': '1qazxsw@',
    # 文件日志目录（与原运维脚本保持一致）
    'LOG_DIR': r'D:\logs\ywops\trust_site',
}

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'resize',
    'domain',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "hpjx.hpjx_sso.SSOMiddleware",
]

ROOT_URLCONF = 'h8667_vmplatform.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'resize.context_processors.sso_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'h8667_vmplatform.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
     'default': {
        'ENGINE': 'hpjx.django.db.engine.mysql',
        'NAME': 'h8667_vm_resize',
        'USER': 'root',
        'PASSWORD': 'xxxxx',
        'HOST': '10.2.xx.xxx',
        'PORT': '3306',
        'TEST': {
            'CHARSET': 'utf8mb4',
            'COLLATION': 'utf8mb4_general_ci',
        },
    }


}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

################################################################################
############################## SSO相关设置 ######################################
################################################################################

# SSO_IS_DEBUG = IS_DEBUG  # 判断是DEV还是prod,如果启用，则使用 DEV_XXXX相关的配置信息。

# # 如果Setting文件有区分开发配置和发布配置
# # 那么SSO_IS_DEBUG = IS_DEBUG 即可，在开发模式的配置中添加DEV_XXX相关的配置，发布配置中使用SSO_XXXX即可

# SSO_USER_INFO_TYPE = 'detail'  # 'detail' | 'simple' 标记跟SSO获取用户信息时，返回简单数据还是详细用户数据

SSO_USER_INFO_TYPE = 'detail'  # 'detail'

SSO_APP_ID = 'h8667_vmplatform'
SSO_APP_SECRET = 'CABC4D89F1B94852B05231A9E4E053BC'
SSO_LOGIN_INDEX_URL = 'sso.4307.com/ctrl/login/'
SSO_USER_INFO_URI = 'sso.4307.com/ctrl/userinfo/'
SSO_GEN_TICKET_URI = 'sso.4307.com/ctrl/ticket/'
SSO_LOGOUT_URI = 'sso.4307.com/ctrl/logout/'

DEV_SSO_APP_ID = 'h8667_vmplatform'
DEV_SSO_APP_SECRET = 'CABC4D89F1B94852B05231A9E4E053BC'
DEV_SSO_LOGIN_INDEX_URL = 'dev.sso.4307.com/ctrl/login/'
DEV_SSO_USER_INFO_URI = 'dev.sso.4307.com/ctrl/userinfo/'
DEV_SSO_GEN_TICKET_URI = 'dev.sso.4307.com/ctrl/ticket/'
DEV_SSO_LOGOUT_URI = 'dev.sso.4307.com/ctrl/logout/'

TOKEN_KEY = 'x-token'
PATCH_SAMESITE_KEYS = [TOKEN_KEY]

